services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sesasi-db
    ports:
      - "5428:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local